// Testimonials in the dithered-portrait style: a horizontal band of big
// rounded cards, a halftone dot portrait on a warm tile, the quote beside
// it, attribution in mono caps. The portraits are photographic halftones
// generated by scripts/halftone.py from AI-generated faces of people who do
// not exist; rerun the script on Allison's and Isaiah's real photos to
// replace them. A soft light sweep animates the dots, stilled under
// reduced motion.

type Person = { name: string; role: string; quote: string; img: string };

const PEOPLE: Person[] = [
  { name: "Allison Yew", role: "Senior attorney", quote: "[ Allison's words go here ]", img: "/portraits/portrait-a.svg" },
  { name: "Isaiah", role: "Paralegal", quote: "[ Isaiah's words go here ]", img: "/portraits/portrait-b.svg" },
];

export function Testimonials() {
  return (
    <div className="quotes" role="list">
      {PEOPLE.map((p) => (
        <article className="quote" role="listitem" key={p.name}>
          <div className="quote-tile">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={p.img} alt="" width={240} height={300} loading="lazy" />
          </div>
          <div className="quote-body">
            <p className="quote-text">&ldquo;{p.quote}&rdquo;</p>
            <div className="quote-attr">{p.name.toUpperCase()}, {p.role.toUpperCase()}</div>
          </div>
        </article>
      ))}
    </div>
  );
}
